FROM golang:1.20-alpine as build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o service

FROM alpine:3.11 as run
COPY --from=build /app/service /

CMD [ "/service" ]

